### ISSUE TITLE
如何组织 TalkElixir 社区

### ISSUE THREAD

**Issue by zhenfeng-zhu** [TalkElixir/night#1]
我们希望可以推进大家深入了解Elixir，快速成长为资深的Alchemist！我们希望每次来了的人和没来的人都能够有收获，成长。

让每个想要学习的人都能参与进来，（包括初中高级Elixir工程师）， 只有层次相当的人才有可能有思维的碰撞和交流，这样最终的产出也尽可能的高质量。

想要参与的同学可以在此issue下报名，当👍🏻大于10个，或者回复报名的同学人数大于5个时，我们就正式发起第一次的讨论，请大家多多转发、分享和参与。

**Comment by leeduckgo** [comment]
Good Job!
