### ISSUE TITLE
【分享计划】快学 Erlang

### ISSUE THREAD

**Issue by zhenyuanlau** [TalkElixir/night#11]
## 快学 Erlang

关于 Erlang 的知识/工具/经验. 面向 Erlang 新手, 希望 Erlang 高手可以提点.

## 分享者自我介绍

一个 Scala && Ruby 工程师.

## 分享时间

2022-06-06 21:00 UTC+8

## 分享地址

https://github.com/zhenyuanlau/erlang-spec

## Slides

https://github.com/zhenyuanlau/erlang-spec/blob/main/resources/Erlang.md

## 参考资料

- Erlang 趣学指南
- Erlang 程序设计(第二版)

**Comment by zhenfeng-zhu** [comment]
Fenix 邀请您参加腾讯会议
会议主题：TalkElixir：快学 Erlang
会议时间：2022/06/06 21:30-22:00 (GMT+08:00) 中国标准时间 - 北京

点击链接入会，或添加至会议列表：
https://meeting.tencent.com/dm/gBCYVjcvLkwC

#腾讯会议：242-698-583

复制该信息，打开手机腾讯会议即可参与
