### ISSUE TITLE
【分享计划】看 Broadway 源码，发现 Bug 的历程

### ISSUE THREAD

**Issue by kenspirit** [TalkElixir/night#15]
## 大纲

* Broadway 是什么?  
* 基本的数据流处理流程及源码  
* 问题：本该并行的框架串行了  
* 问题源码分析  

## 分享者自我介绍

* Blog: https://www.thinkingincrowd.me/
* Github: https://github.com/kenspirit
* Bio: 
  * 船运行业，基于 Fabric 联盟链的平台开发。
  * Node.js/JAVA 为主，自顾自玩 Elixir 的老爹。
  * 练习拳击中

## 分享时间

2022-06-17 20:30 UTC+8

## 分享地址

https://www.thinkingincrowd.me/nodeppt/

## Slides

https://www.thinkingincrowd.me/nodeppt/broadway_pr.html#slide=1

## 参考资料

[Tuning Broadway RabbitMQ Pipelines for Latency](https://dockyard.com/blog/2021/06/24/tuning-broadway-rabbitmq-pipelines-for-latency?utm_medium=email&utm_source=elixir-radar)

[Broadway Source Reading (Part 1 - Entry Point and Architecture)](https://www.thinkingincrowd.me/2021/03/30/broadway-source-reading-entry-and-architecture/)

[PR to Broadway](https://github.com/dashbitco/broadway/pull/271)

[PR to GenStage](https://github.com/elixir-lang/gen_stage/pull/277)

----

## 备注

针对此次分享的 QA 请分享者在分享之后，整理同步到此 issues 后面。

**Comment by zhenfeng-zhu** [comment]
Fenix 邀请您参加腾讯会议
会议主题：Fenix预定的会议
会议时间：2022/06/17 20:30-21:30 (GMT+08:00) 中国标准时间 - 北京

点击链接入会，或添加至会议列表：
https://meeting.tencent.com/dm/RuHo7UfOQPk5

#腾讯会议：255-818-639

复制该信息，打开手机腾讯会议即可参与
