### ISSUE TITLE
我想听一个你们当初是怎么进入学习 Elixir .是生活需要,还是老板需要【分享计划】

### ISSUE THREAD

**Issue by Sarah19han** [TalkElixir/night#17]
## <话题名称>

（对本期分享话题做一个简短说明。）

## 分享者自我介绍

你的名字，来自哪家公司，担任什么职务，Elixir 所承载的数据量等各方面。

## 分享时间

20XX-YY-ZZ 21:00 UTC+8

## Slides

（尽量使用可在线预览的幻灯片）

## 参考资料

（你可以列出本次分享所涉及的参考资料，以便大家更好的预习。）

----

## 备注

针对此次分享的 QA 请分享者在分享之后，整理同步到此 issues 后面。

**Comment by zhenfeng-zhu** [comment]
抱歉你这个issue没有按照格式提出，先close啦
