### ISSUE TITLE
【分享计划】Zig 写 NIF 的新玩法

### ISSUE THREAD

**Issue by jackalcooper** [TalkElixir/night#18]
## Zig 写 NIF 的新玩法

介绍用 Zig 来写 NIF 的一些新发现和心得体会

## 分享者自我介绍

Jackal. 最近在开发一个把 LLVM/MLIR 放到 Elixir 来跑的库。

## 分享时间

2022-08-14 16:00 UTC+8

## Slides

（尽量使用可在线预览的幻灯片）

## 参考资料

https://ziglang.org/documentation/master/#Introduction
https://github.com/rusterlium/rustler

----

## 备注

针对此次分享的 QA 请分享者在分享之后，整理同步到此 issues 后面。

**Comment by zhenfeng-zhu** [comment]
Fenix 邀请您参加腾讯会议
会议主题：TalkElixir：Zig 写 NIF 的新玩法
会议时间：2022/08/14 16:00-16:45 (GMT+08:00) 中国标准时间 - 北京

点击链接入会，或添加至会议列表：
https://meeting.tencent.com/dm/CVFFb4oftfxO

#腾讯会议：973-101-386

手机一键拨号入会
+8675536550000,,973101386 (中国大陆)
+85230018898,,,2,973101386 (中国香港)

根据您的位置拨号
+8675536550000 (中国大陆)
+85230018898 (中国香港)

复制该信息，打开手机腾讯会议即可参与

**Comment by zhenfeng-zhu** [comment]
https://calendar.google.com/event?action=TEMPLATE&tmeid=dDYwMGY2MGI4ZW9wODB1YzYzNThnbnAyMDAgemh1emhlbmZlbmcxOTkzQG0&tmsrc=zhuzhenfeng1993%40gmail.com
